APP/ckdApp/urls.py
from django.conf.urls import url
from ckdApp import views
from django.urls import path

app_name = 'ckdApp'

urlpatterns = [
    path('', views.dataUploadView.as_view(), name = 'ckd'),
    #path('whats', views.WhatsappAnalaysis.as_view(), name = 'whats'),
    #path('result', views.finalresult.as_view(), name= 'result'),
    #path('success', views.Success.as_view(), name = 'success'),
    #path('fail',views.Failure.as_view(),name='fail'),
    #path('filenot',views.FileNotfound.as_view(), name='filenot'),
    #path('aboutus',views.AboutUs.as_view(), name='aboutus')
]

APP/ckdProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from ckdApp import views
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('/',include('ckdApp.urls',namespace='ckdApp')),
    #path('', views.FileUploadView.as_view(), name = 'image_upload'),
    #path('whats', views.WhatsappAnalaysis.as_view(), name = 'whats'),
    path('', views.dataUploadView.as_view(), name= 'ckd'),
    #path('success', views.Success.as_view(), name = 'success'),
    #path('fail',views.Failure.as_view(),name='fail'),
    #path('filenot',views.FileNotfound.as_view(), name='filenot'),
    #path('aboutus',views.AboutUs.as_view(), name='aboutus')
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

APP/ckdApp/models.py
from django.db import models

class ckdModel(models.Model):
    Open_Circuit_Voltage_input = models.FloatField()
    Maintenance_History_Neglected_input = models.FloatField()
    Maintenance_History_No_maintenance_input = models.FloatField()
    Maintenance_History_Regular_maintenance_input = models.FloatField()
    Acid_Level_Check_Normal_input = models.FloatField()

    def __str__(self):
        return str(self.pk)

APP/ckdApp/forms.py
from django import forms
from .models import *



class ckdForm(forms.ModelForm):
    class Meta():
        model=ckdModel
        fields=['Open_Circuit_Voltage_input','Maintenance_History_Neglected_input','Maintenance_History_No_maintenance_input','Maintenance_History_Regular_maintenance_input','Acid_Level_Check_Normal_input']

APP/ckdApp/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect
#from .forms import *
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import (View,TemplateView,
ListView,DetailView,
CreateView,DeleteView,
UpdateView)
from . import models
from .forms import *
from django.core.files.storage import FileSystemStorage
#from topicApp.Topicfun import Topic
#from ckdApp.funckd import ckd
#from sklearn.tree import export_graphviz #plot tree
#from sklearn.metrics import roc_curve, auc #for model evaluation
#from sklearn.metrics import classification_report #for model evaluation
##from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(df2.drop('classification_yes', 1), df2['classification_yes'], test_size = .2, random_state=10)

import time
import pandas as pd
import numpy as np
#from sklearn.preprocessing import StandardScaler
#from sklearn.feature_selection import SelectKBest
#from sklearn.feature_selection import chi2
#from sklearn.model_selection import train_test_split
#from sklearn.decomposition import PCA
#from sklearn.feature_selection import RFE
#from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
#import eli5 #for purmutation importance
#from eli5.sklearn import PermutationImportance
#import shap #for SHAP values
#from pdpbox import pdp, info_plots #for partial plots
np.random.seed(123) #ensure reproduc
class dataUploadView(View):
    form_class = ckdForm
    success_url = reverse_lazy('success')
    template_name = 'create.html'
    failure_url= reverse_lazy('fail')
    filenot_url= reverse_lazy('filenot')
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
    def post(self, request, *args, **kwargs):
        #print('inside post')
        form = self.form_class(request.POST, request.FILES)
        #print('inside form')
        if form.is_valid():
            form.save()
            data_ocv= request.POST.get('Open_Circuit_Voltage_input')
            data_mh=request.POST.get('Maintenance_History_Neglected_input')
            data_mhm=request.POST.get('Maintenance_History_No_maintenance_input')
            data_mhr=request.POST.get('Maintenance_History_Regular_maintenance_input')
            data_acl=request.POST.get('Acid_Level_Check_Normal_input')
            #print (data)
            #dataset1=pd.read_csv("prep.csv",index_col=None)
            dicc={'yes':1,'no':0}
            filename = 'Decision_tree_BATTERY_final.sav'
            classifier = pickle.load(open(filename, 'rb'))

            data = np.array([data_ocv,data_mh,data_mhm,data_mhr,data_acl])
            #sc = StandardScaler()
            #data = sc.fit_transform(data.reshape(-1,1))
            out=classifier.predict(data.reshape(1,-1))
# providing an index
            #ser = pd.DataFrame(data, index =['bgr','bu','sc','pcv','wbc'])

            #ss=ser.T.squeeze()
#data_for_prediction = X_test1.iloc[0,:].astype(float)

#data_for_prediction =obj.pca(np.array(data_for_prediction),y_test)
            #obj=ckd()
            ##plt.savefig("static/force_plot.png",dpi=150, bbox_inches='tight')







            return render(request, "succ_msg.html", {'data_ocv':data_ocv,'data_mh':data_mh,'data_mhm':data_mhm,'data_mhr':data_mhr,'data_acl':data_acl,
                                                        'out':out})


        else:
            return redirect(self.failure_url)

APP/ckdApp/templates/aboutus.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="jumbotron">
      <h1>Welcome to Analysis World</h1>
      <p>Here you can Analysis your whatsapp chat</p>
    </div>

{% endblock %}

APP/ckdApp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <style>
    body {
      background-image: url("{% static 'output_image/backgroud.PNG' %}");
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: 100% 100%;
          }
    .navbar-default {
    background-color: #075E54;
    border-color: #030033;
}

    </style>
  </head>
  <body>

    <nav class="navbar navbar-expand-sm navbar-default navbar-dark">
  <!-- Brand -->
      <a class="navbar-brand" href="{% url 'ckdApp:ckd' %}">Home</a>

      <!-- Links -->
      <ul class="navbar-nav">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'ckdApp:ckd' %}">CKD</a>
        </li>

      </ul>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}

    </div>
  </body>

</html>

APP/ckdApp/templates/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="jumbotron">
  <h1>Predictive Maintenance System for Battery Health Monitoring</h1>
  <head>
    Please enter repective fields
  </head>

    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">upload</button>
    </form>
  </div>
{% endblock %}

APP/ckdApp/templates/fail.html
{% extends 'base.html' %}

{% block body-content %}
{% load staticfiles %}

    <h1>Please upload Whatsapp .Text file</h1>
    <a  href="{% url 'app_uplaod:image_upload' %}">Upload_TextFile</a>
{% endblock %}

APP/ckdApp/templates/filenot.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Please rename your file name</h1>
  </body>
</html>

APP/ckdApp/templates/out.html
{% extends 'base.html' %}

{% block body_block %}
{% load static %}
<div class="jumbotron">


<h1>Topic Modelling</h1>
<br>
  {% for i,index ,topic in topiresult.itertuples %}
    {{index}}:{{topic}}
<br>
  {%endfor%}

<h1>Sentimental Report and Wordcloud</h1>

      <h2>Echo_ White</h2>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'sentimental_image/sentiment_Echo_White.png' %}"/>
      <br>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'wordcloudimage/wordcloud_Echo_White.PNG' %}"/>
      <br>
      <h2>Fire 8 HD</h2>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'sentimental_image/sentiment_Fire8HD.png' %}"/>
      <br>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'wordcloudimage/wordcloud_Fire8HD.PNG' %}"/>
      <br>
      <h2>Fire Tablet for kids 7</h2>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'sentimental_image/sentiment_Firekids7.png' %}"/>
      <br>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'wordcloudimage/wordcloud_Firekids7.PNG' %}"/>
      <br>
      <h2>FireTV</h2>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'sentimental_image/sentiment_FireTV.png' %}"/>
      <br>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'wordcloudimage/wordcloud_FireTV.PNG' %}"/>
      <br>
      <h2>Fire Table 7</h2>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'sentimental_image/sentiment_FireTablet_7.png' %}"/>
      <br>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'wordcloudimage/wordcloud_FireTablet_7.PNG' %}"/>
      <br>
      <h2>Kindle Fire 10</h2>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'sentimental_image/sentiment_KindelFire10.png' %}"/>
      <br>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'wordcloudimage/wordcloud_KindelFire10.PNG' %}"/>
      <br>

{%endblock%}
</div>

APP/ckdApp/templates/process.html
{% extends 'base.html' %}

{% block body_block %}
{% load static %}
<div class="">
  <br>
  <br>
</div>
<table class="table table-dark table-striped table-left" align="left">
            <tr>
              <th>Sl.No</th>
              <th>Date</th>
              <th>Time</th>
              <th>Text</th>
              <th>Name</th>
              <th>Scores</th>
              <th>compound</th>
              <th>Negetive</th>
              <th>Positive</th>
              <th>Netural</th>
              <th>comp_score</th>
              <th>Topic</th>
            </tr>
            {% for slno,date,time,text,name,scores,compound,negetive,positive, neutral,compscore,topic in dataset.itertuples %}


            <tr>
              <td>{{slno}}</td>
              <td> {{date}}</td>
              <td>{{time}}</td>
              <td>{{text}} </td>
              <td>{{name}}</td>
              <td>{{scores}}</td>
              <td>{{compound}}</td>
              <td>{{negetive}}</td>
              <td>{{positive}}</td>
              <td>{{neutral}}</td>
              <td>{{compscore}}</td>
              <td>{{topic}}</td>
            </tr>

            {% endfor%}

      </table>

{% endblock %}

APP/ckdApp/templates/ref.html
{% extends 'base.html' %}

{% block body_block %}
{% load staticfiles %}
<div class="jumbotron">
    <h1>Well Done!! </h1>
    <div class="fieldWrapper">
    <p><strong>Talkative</strong>: {{result.0}}</p>
    <p><strong>Less Talkative</strong>: {{result.1}}</p>
    {% if not result1 %}
      <p><strong>Filrt Percentage by </strong> {{result.0}}: Wonderfull No Filrting</p>
    {% else %}
      <p><strong>Filrt Percentage by </strong> {{result.0}}: {{result.2}}</p>
    {% endif %}
    {% if not result1  %}
      <p><strong>Filrt Percentage by </strong> {{result.1}}: Wonderfull No Filrting</p>
    {% else %}
      <p><strong>Filrt Percentage by </strong> {{result.1}}: {{result.3}}</p>
    {% endif %}
    <p><strong>Most Active Date</strong>: {{stats.0}}</p>
    <p><strong>Most Active Day</strong>: {{stats.1}}</p>
    <p><strong>Most Active Hour</strong>: {{stats.2}}</p>
    <p><strong>Average Number of Message per Day</strong>: {{stats.3}}</p>
    <p><strong>Media Shared Freak</strong>: {{stats1.0}}</p>
    <p><strong>Message Deleted Freak</strong>: {{stats1.1}}</p>
    <p><strong>Missed Voice Call Count</strong>: {{stats1.2}}</p>
    <p><strong>Missed Video Call Count</strong>: {{stats1.3}}</p>
    <p>DateWise Message Count</p>
    <img src="date_chart.png" alt="Date_Chart">
    {% if media_count == "No Media were shared" %}
      <p><strong>Media Count</strong>: {{media_count}}</p>
    {% else %}
      <p><strong>Media Count</strong>
        <img src="media_count.png" alt="media_count">
    {% endif %}
    {% if msg_deleted_count == "No message was deleted" %}
      <p><strong>Deleted message Count</strong>: {{msg_deleted_count}}</p>
    {% else %}
      <p><strong>Deleted message Count</strong>:</p>
      <img src="msg_deleted_count.png" alt="msg_deleted_count">
    {% endif %}
    {% if voice_call_count == "No Missed Voice Call" %}
      <p><strong>Missed Voice Call Count:</strong>: {{voice_call_count}}</p>
    {% else %}
      <p><strong>Missed Voice Call Count:</strong>:</p>
      <img src="voice_call_count.png" alt="voice_call_count">
    {% endif %}
    {% if video_call_count == "No Missed Video Call"%}
      <p><strong>Missed Video Call Count:</strong>: {{video_call_count}}</p>
    {%else%}
      <p><strong>Missed Voice Call Count:</strong>:</p>
      <img src="video_call_count.png" alt="video_call_count">
    {% endif %}
    </div>

    <a  href="{% url 'app_uplaod:image_upload' %}">Upload_TextFile</a>
</div>
{% endblock %}

APP/ckdApp/templates/succ_msg.html
{% extends 'base.html' %}

{% block body_block %}
{% load static %}
<div class="jumbotron">
    <h1>Predictive Maintenance System for Battery Health Monitoring </h1>
    <div class="fieldWrapper">
      <h2>For the values</h2>
      <p>Open_Circuit_Voltage_input:{{data_ocv}}</p>
      <p>Maintenance_History_Neglected_input:{{data_mh}}</p>
      <p>Maintenance_History_No_maintenance_input:{{data_mhm}}</p>
      <p>Maintenance_History_Regular_maintenance_input:{{data_mhr}}</p>
      <p>Acid_Level_Check_Normal_input:{{data_acl}}</p>
      <br>
      {% if out == 1 %}
        <p>You <b>will have</b>  Maintenance Required in the future: <b>yes</b></p>
      {% else %}
        <p>You <b>will not</b> have Maintenance Required in the future:<b>No</b></p>

      {% endif %}

    <a  href="{% url 'ckdApp:ckd' %}">Predictive Maintenance System for Battery Health Monitoring</a>
    <br>
</div>
{% endblock %}